### ISSUE TITLE
The touchpad ON/OFF switch Fn key is not functional

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#38]
*Issue moved from GitLab*

**Dasharo version**

v0.1.2

**Hardware details**

Clevo NV41MZ

**Affected component(s) or functionality**

Touchpad ON/OFF hotkey

**Brief summary**

The touchpad ON/OFF switch Fn key is not functional

**How reproducible**

Issue occurs every time the hotkey is pressed

**How to reproduce**

1. Press the touchpad ON/OFF hotkey

**Expected behavior**

Touchpad is disabled/enabled

**Actual behavior**

Nothing happens

**Screenshots**

**Additional context**

**Solutions you've tried**

/cc @macpijan

**Comment by macpijan** [comment]
This was resolved as a documentation workaround implemented in documentation here: https://gitlab.com/novacustom/dasharo-compatibility/-/issues/1#note_810992892

**Comment by mkopec** [comment]
Reopening this issue, since it seems to affect ns50mu now.

**Comment by wessel-novacustom** [comment]
The same workaround can be applied here.

https://gitlab.com/novacustom/dasharo-compatibility/-/issues/1#note_810992892

**Comment by sulewskiprzemyslaw** [comment]
The same problem occurs on the platform NS70

**Comment by wessel-novacustom** [comment]
The same problem occurs on all Clevo based laptops with the 11th generation Intel Core CPU.

For laptops with these criteria, the problem can be fixed if you download the attached script and **move it to the home folder**.

[fixtouchpad.txt](https://github.com/Dasharo/dasharo-issues/files/8798823/fixtouchpad.txt)

Then, open a terminal and run:

_chmod +x fixtouchpad.txt_
_sudo ./fixtouchpad.txt_

**Comment by choybe** [comment]
https://github.com/Dasharo/dasharo-issues/issues/38#issuecomment-1141182040
works well. After reboot.

**Comment by wessel-novacustom** [comment]
Ah yes, I forgot that. Thanks!

**Comment by sulewskiprzemyslaw** [comment]
@mkopec 

> Reopening this issue, since it seems to affect ns50mu now.

Hey, could you confirm that the problem on the latest firmware version (v.1.3.0) is not occurring?

**Comment by mkopec** [comment]
@sulewskiprzemyslaw Yes, this has been fixed in v1.3.0

**Comment by choybe** [comment]
honestly, I do not understand how to update from my current version 1.2 to 1.3:
I cannot find an explanation about. Shouldn't it work automatically (it doesn't) . How to do the manually? Thanks for some better hints.

**Comment by choybe** [comment]
I feel somehow as a dummy with this update fro, 1.2 to 1.3 and do not understand nothing at all
When following the update instructions, I get the following error message. No idea how to understand this message. 

$ sudo fwupdmgr refresh
WARNING: UEFI capsule updates not available or enabled in firmware setup
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
Firmware metadata last refresh: 2 hours ago. Use --force to refresh again.

**Comment by pietrushnic** [comment]
@choybe because v1.3.0 coming also with open-source embedded controller firmware and update procedure is little bit more complex. Please check release notes and read about EC firmware transition [here](https://docs.dasharo.com/variants/novacustom_ns5x_7x/releases/).

**Comment by choybe** [comment]
thank you for your hint. But I still don't understand absolutely nothing on how to update. 
the fail starts with the error message ec_transition: Command not found
What I did: I opened my ubuntu 22 terminal downloaded with wget the rom files as requested and that was it  - all ended with the error message above. 
It seems to me that this dasharo and EC firmware transition is moreover for expert on hardware intergration than for simple linux consumers. But it cannot be a solution that I have to bring for a simple update my notebook to an expert. I use to make regular updates on my linux software with need of studies for hours to understand what the help could mean to say. Why this isn't possible with this dasharo firmware? Isn't there a way to automatically update the firmware, lilke so much other notebooks hardware do?

**Comment by pietrushnic** [comment]
@choybe everything is possible with resources. We are really sorry you have unpleasant experience with last release. With every release we working on improving user experience.

Regarding `ec_transition: Command not found`, please note this command is not included in Ubuntu. It is included in 3mdeb [Dasharo Tools Suite Community Edition](https://docs.dasharo.com/common-coreboot-docs/dasharo_tools_suite/) Linux distribution dedicated to simplify any operations related to firmware. [Here](https://docs.dasharo.com/common-coreboot-docs/dasharo_tools_suite/#bootable-usb-stick) is provedure how to preapre USB stick. We are sorry, but for such complext operation like switch from proprietary EC firmware to open-source one, we don't have easier solution now.

**Comment by choybe** [comment]
It won't work this way ! 
`    flash the downloaded image onto USB stick,
        you can use cross-platform GUI installer - [Etcher](https://www.balena.io/etcher/)
        you can also use dd to flash from command line
gzip -cdk dts-base-image-ce-v1.0.0.wic.gz | \
sudo dd of=/dev/sdX bs=16M status=progress conv=fdatasync`
After download neither with command dd neither with GUI Either it is writable to the USB disk

Sorry, but this way it cannot work for a dummy like me. I make surely a wrong step anywhere. 
With either I get the message sda/dev not writable. with dd the message no such file or directory (sdX). 

So just continue very lost about. Sorry to say.

**Comment by choybe** [comment]
It is complicate: With some efforts (took me a half hour) I could build the bootable USB-Stick (with Ethher - terminal command dd didn't worked at all). After reboot with the USB I arrived somehow in the dasharo shell but fwupdmgr refresh / fwupdmgr update didn't worked at all. 
No way to update. Something wrong with the version it say. 
Isn't there a network solution? Last time I was promised by the hardware seller the version 1.2 I run can now update automatically dasharo. But as it looks it cannot even update with cryptic shell commands. It is somehow frustrating.

**Comment by choybe** [comment]
PS perhaps a simple error by my side? Do I have to connect the Ethernet cable to my WLAN router when trying to update via Boot-Disk?

**Comment by wessel-novacustom** [comment]
Hello,

Yes - an internet connection via Ethernet is required.

I am not sure if you are on my email list for Dasharo v1.3.0, but I am preparing step-by-step instructions for the transition to open EC and Dasharo v1.3.0. If I am right, you have my email address.

Once these instructions have been verified, I will publish them here too.

**Comment by choybe** [comment]
Hi, it took me a while to find a moment to try to update with ethernet. In between, I had first to by an ethernet cable, for I do not need this cable any more since years. But then again it failed with the update via usb-stick and ethernet :-(
$ fwupddmgr refresh works - BUT - $ fwupdmgr update fails with the message that two devices are not recognized.

**Comment by Pokisiekk** [comment]
Using a script form [here](https://docs.dasharo.com/unified/clevo/post-install/#touchpad-hotkey-enablement) makes the touchpad ON/OFF switch Fn key is functional.
