### ISSUE TITLE
F7 Function Key controlled by the firmware

### ISSUE THREAD

**Issue by MasterBootRecord-KML** [Dasharo/dasharo-issues#391]
**Dasharo version**
v1.4.0

**Dasharo variant**
 NovaCustom NV40MZ (Tiger Lake variant) running GNOME and Arch Linux.

**Question text**
Actually, when using the F7 function key, the multi-display switch function seems to be controlled mainly by the firmware and not the OS. 
When using this key, normally it should be the opposite (if I'm right) : the OS should tell the firmware to switch display mode.
Is it a bug and do I need to make a bug report or is it normal ?
I must specify that there is no problem whatsoever as the display mode changes when the key is pressed.

**Comment by macpijan** [comment]
>  seems to be controlled mainly by the firmware and not the OS.

Can you please elaborate what do you mean by that?

How do you judge, whether it is `controlled by firmware` or `controller by OS`?

**Comment by MasterBootRecord-KML** [comment]
On GNOME, when you press the key to change the display mode (F7), there is a window that opens to let you chose the display mode you want to select. But in the case of the NV40MZ, the display mode changes before the window opens and there is no entry in the journal that informs of the changed display mode. So I deducted the firmware changed the display mode before the OS but I may be wrong.

Here's what the display switcher window I talked should look like :
![screenshot_1030](https://user-images.githubusercontent.com/117741516/226402794-853158b4-e576-4a19-b464-80c757d6148d.jpg)

**Comment by miczyg1** [comment]
@MasterBootRecord-KML that may depend on the keycodes interpreted by GNOME/Linux. We had to specify the keycodes for touchpad toggle to be interpreted like that: https://docs.dasharo.com/unified/clevo/post-install/

Our firmware by itself has no way to switch screens neither has any implementation to do so. Anyway, we will look into it, because such pop-up window should really appear when the hotkey is pressed.

**Comment by MasterBootRecord-KML** [comment]
Ok.
I have been thinking about this and that might be a matter of delay. Maybe that increasing a bit the delay before changing the display mode might let GNOME the time to display its window : it's the case on my other laptop (ThinkPad P50 with its propietary bios) when pressing the F7 key.

**Comment by miczyg1** [comment]
On Ubuntu I can see such pop-up just briefly and it doesn't let the user select the mode, it immediately switches outputs instead. SO this might be the real problem here. Not sure what causes it yet.

**Comment by miczyg1** [comment]
@mkopec I found this: https://github.com/Dasharo/coreboot/blob/clevo/develop/src/ec/system76/ec/acpi/ec.asl#L41
Before open EC we were using the software mechanism which let the OS handle the display change. Now we use hardware mechanism and the hotkeys no longer work as before. Why is that?

**Comment by mkopec** [comment]
@miczyg1 there is no hardware mechanism. Pressing Fn+F7 emits Win+P, but only keeps the P pressed for a very short moment, thus switching the displays immediately instead of displaying a popup like in the previous closed EC versions. This can certainly be fixed in EC firmware

**Comment by miczyg1** [comment]
So all we have to do is keep emitting the P being pressed as long as Fn is pressed?

**Comment by philipanda** [comment]
Still an issue on NS5x/7x TGL and NV41MZ on v1.6.0-rc3.

The display switch popup never appears. The modes just switch immediately.
In order for the popup to stay using super+P, the super key needs to be held down.

> So all we have to do is keep emitting the P being pressed as long as Fn is pressed?

Not "P" but "Super/Windows"
